name: build_manually

on:
  issue_comment:
    types: [created, edited, deleted]

    branches:
      - master

jobs:
  build_py_wheel:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '/build')"

    steps:
      - name: say hi
        run: echo hi
