name: build_manually

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  build_py_wheel:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/build')
    runs-on: ubuntu-latest

    steps:
      - name: say hi
        run: echo hi
