name: build_manually

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  cmake-build-manually:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/build')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - uses: actions/upload-artifact@v2
        with:
          name: build_${{github.sha}}.zip
          path: ${{github.workspace}}/build/main
