name: build_manually

on:
  issue_comment:
    types: [created, edited, deleted]

    branches:
      - master

jobs:
  build_py_wheel:
    if: contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest

    steps:
      - name: say hi
        run: echo hi
